add_newline = false
command_timeout = 200
format = "[${custom.venv}$directory$git_branch$git_status]($style)$character"

[character]
error_symbol = "[λ](bold red)"
success_symbol = "[λ](bold fg:231)"

[directory]
truncation_length = 1
truncation_symbol = ""
style = "bold fg:195"
repo_root_style = "bold fg:183"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic fg:248"

[git_status]
format     = '[$all_status]($style)'
style      = "fg:221"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "* "
modified   = "Δ "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = "x "

[custom.venv]
format = '[# ]($style)'
style = "fg:181"
when = "test -n \"$VIRTUAL_ENV\""
